### PR TITLE
TC updates October/November

### PR DESCRIPTION
**Pull request by Hobbesball**
Here's another halloweeny TC query update, including:

- updates to Archaeology TC to remove unwanted provider
- big update to the Sports TC to shorten query, improve terms used, sanitize translations

💀🍁☠🎃👻🎃🍁

### CODE REVIEW

**Comment by Hobbesball** [comment]
@marrerom would it be possible to merge this into master in the near future? If your workload allows it, of course.

**Comment by marrerom** [comment]
Sure! It is planned for 9 Dec, sorry I forgot to inform you.

**Comment by marrerom** [comment]
Done, please check!

**Comment by Hobbesball** [comment]
all seems good, thanks Monica, and happy holidays when you get there!

**Pull request merged**
